version: "3.7"
services:
  postgres:
    env_file: .env
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    volumes:
      - docker-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - music-social
  postgres-test:
    env_file: .env.test.local
    container_name: postgres-test
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - docker-postgres-test:/var/lib/postgresql/data
    ports:
      - "5433:5432" # порт для тестовой базы данных
    networks:
      - music-social
volumes:
  docker-postgres:
  docker-postgres-test:
networks:
  music-social: